openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Fresh Rotten Fruits Classifier API"
  description: "API for classifying fresh and rotten fruits using a pre-trained TensorFlow model."

paths:
  /:
    get:
      summary: "Get a greeting message"
      responses:
        "200":
          description: "Successful response"
          content:
            text/plain:
              schema:
                type: "string"
      tags:
        - "Greeting"

  /api:
    post:
      summary: "Process an image and classify fresh or rotten fruit"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                image:
                  type: "string"
                  format: "binary"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  result:
                    type: "string"
                    description: "Classified result (Fresh or Rotten)"
      tags:
        - "Image Processing"

components:
  schemas:
    ErrorResponse:
      type: "object"
      properties:
        message:
          type: "string"
